# Generated by Django 3.2.5 on 2021-07-23 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('englishname', models.CharField(max_length=50)),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d')),
                ('dept', models.CharField(max_length=50)),
                ('organs', models.CharField(max_length=50)),
                ('sex', models.CharField(max_length=5)),
                ('rank', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=50)),
                ('studyexp', models.CharField(max_length=1000)),
                ('researchfield', models.CharField(max_length=100)),
                ('papers', models.CharField(max_length=1500)),
                ('tasks', models.CharField(max_length=1000)),
                ('honors', models.CharField(max_length=150)),
            ],
        ),
    ]
