# Generated by Django 3.2.5 on 2021-07-23 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_alter_teacher_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='show',
            field=models.BooleanField(default=True),
        ),
    ]
