# Generated by Django 3.2.5 on 2021-07-24 07:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcomments', '0002_alter_tcomments_user_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('user_name', models.CharField(max_length=100)),
                ('teacher_id', models.IntegerField()),
                ('stars', models.IntegerField()),
                ('message', models.TextField(blank=True)),
                ('comment_date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.DeleteModel(
            name='TComments',
        ),
    ]
