# Generated by Django 3.2.5 on 2021-07-24 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcomments', '0003_auto_20210724_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='tcomment',
            name='teacher_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='tcomment',
            name='user_name',
            field=models.CharField(max_length=30),
        ),
    ]
